### ISSUE TITLE
NullPointerException in org.mariadb.r2dbc.MariadbRow.<init>

### ISSUE THREAD

**Issue by vnguyen972** [mariadb-corporation/mariadb-connector-r2dbc#29]
Hi, I am new to this driver and I ran into this exception once a while... and I'm not sure why...

Any help would be appreciated.

Here's a snippet of the code - it doesn't throw all the time, but if I re-run it multiple times... it would throw the exception once a while.. sometimes more often than not...

Thanks.

PS: Forgot to mention the driver version: 
---
    
**implementation 'org.mariadb:r2dbc-mariadb:1.0.2'**

--

```
Mono<List<SelectorEntity>> selectors = client.sql(queryIdentitySelectors)
                .bind("organizationId", orgId)
                .fetch()
                .all()
                .buffer()
                .next()
                .map(rows ->
                        rows.stream()
                                .map(row -> {
                                    SelectorEntity selectorEntity = new SelectorEntity();
                                    selectorEntity.setLabel((String) row.get("label"));
                                    selectorEntity.setDescription((String) row.get("description"));
                                    selectorEntity.setState(ContentState.valueOf((String) row.get("state")));
                                    selectorEntity.setWhitelistId((Long) row.get("whitelist_id"));
                                    selectorEntity.setUuid((String) row.get("uuid"));
                                    selectorEntity.setId((Long) row.get("id"));
                                    selectorEntity.setGlobal((Boolean) row.get("is_root"));
                                    return selectorEntity;
                                })
                                .collect(Collectors.toList())
                );
```

```
java.lang.NullPointerException: null
	at org.mariadb.r2dbc.MariadbRow.<init>(MariadbRow.java:27) ~[r2dbc-mariadb-1.0.2.jar:1.0.2]
	at org.mariadb.r2dbc.MariadbResult.lambda$map$2(MariadbResult.java:120) ~[r2dbc-mariadb-1.0.2.jar:1.0.2]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:77) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:660) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:738) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:780) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:259) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at org.mariadb.r2dbc.client.MariadbPacketDecoder.handleBuffer(MariadbPacketDecoder.java:98) ~[r2dbc-mariadb-1.0.2.jar:1.0.2]
	at org.mariadb.r2dbc.client.MariadbPacketDecoder.decode(MariadbPacketDecoder.java:79) ~[r2dbc-mariadb-1.0.2.jar:1.0.2]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-transport-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_282]
```

## Also this exception:

```
java.lang.ArrayIndexOutOfBoundsException: 4
	at org.mariadb.r2dbc.MariadbResult.lambda$map$2(MariadbResult.java:106) ~[r2dbc-mariadb-1.0.2.jar:1.0.2]
	at reactor.core.publisher.FluxHandle$HandleSubscriber.onNext(FluxHandle.java:96) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxTakeUntil$TakeUntilPredicateSubscriber.onNext(FluxTakeUntil.java:77) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drainRegular(FluxWindowPredicate.java:660) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.drain(FluxWindowPredicate.java:738) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxWindowPredicate$WindowFlux.onNext(FluxWindowPredicate.java:780) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxWindowPredicate$WindowPredicateMain.onNext(FluxWindowPredicate.java:259) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.drain(FluxCreate.java:793) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxCreate$BufferAsyncSink.next(FluxCreate.java:718) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at reactor.core.publisher.FluxCreate$SerializedSink.next(FluxCreate.java:153) ~[reactor-core-3.3.16.RELEASE.jar:3.3.16.RELEASE]
	at org.mariadb.r2dbc.client.MariadbPacketDecoder.handleBuffer(MariadbPacketDecoder.java:98) ~[r2dbc-mariadb-1.0.2.jar:1.0.2]
```

**Comment by vnguyen972** [comment]
Upgraded to 'org.mariadb:r2dbc-mariadb:1.1.0-beta' seems to resolve the issue...

I'll have to keep watch on this for a while to see if it ever happens; but for the time being... I haven't seen the issue yet.

Thanks.

**Comment by rusher** [comment]
@vnguyen972  just to follow, did this issue occurs since ?

**Comment by rusher** [comment]
closing since no answer
