### ISSUE TITLE
There is an  concurrently NegativeArraySizeException bug with ColumnDefinitionPacket

### ISSUE THREAD

**Issue by mindfn** [mariadb-corporation/mariadb-connector-r2dbc#36]
r2dbc-mariadb version=1.1.2

[DecoderState](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/blob/master/src/main/java/org/mariadb/r2dbc/client/DecoderState.java) .COLUMN_COUNT is a stateful object.
The columnCountPacket property allows concurrent modification by different threads，which can lead to subsequent parsing errors.

```java
  COLUMN_COUNT {
    ColumnCountPacket columnCountPacket;

    @Override
    public ServerMessage decode(ByteBuf body, Sequencer sequencer, ServerMsgDecoder decoder) {
      columnCountPacket = ColumnCountPacket.decode(sequencer, body, decoder.getContext());
      decoder.setStateCounter(columnCountPacket.getColumnCount());
      return columnCountPacket;
    }

    @Override
    public DecoderState next(ServerMsgDecoder decoder) {
      if (columnCountPacket.isMetaFollows()) return COLUMN_DEFINITION;
      if ((decoder.getClientCapabilities() & Capabilities.CLIENT_DEPRECATE_EOF) > 0) {
        return ROW_RESPONSE;
      } else {
        return EOF_INTERMEDIATE_RESPONSE;
      }
    }
  }
```

How the problem happened?
T1 -> Thread1 get  COLUMN_COUNT
T2 -> Thread2 get same  COLUMN_COUNT
T3 -> Thread1 update COLUMN_COUNT's attr columnCountPacket (columnCountPacket1)
T4 -> Thread2 update COLUMN_COUNT's attr columnCountPacket  (columnCountPacket2)

Finally, the attribute of COLUMN_COUNT becomes columnCountPacket2
later , thread1 will rely on wrong columnCountPacket2 causing COLUMN_DEFINITION#decode fail.

Such error occur:
```java
java.lang.NegativeArraySizeException: null
        at org.mariadb.r2dbc.message.server.ColumnDefinitionPacket.decode(ColumnDefinitionPacket.java:156)
        at org.mariadb.r2dbc.client.DecoderState$8.decode(DecoderState.java:128)
        at org.mariadb.r2dbc.client.ServerMsgDecoder.decode(ServerMsgDecoder.java:57)
        at org.mariadb.r2dbc.client.SimpleClient$ServerMessageSubscriber.onNext(SimpleClient.java:584)
        at org.mariadb.r2dbc.client.SimpleClient$ServerMessageSubscriber.onNext(SimpleClient.java:546)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
        at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
        at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
        at reactor.netty.channel.FluxReceive.drainReceiver(FluxReceive.java:279)
        at reactor.netty.channel.FluxReceive.onInboundNext(FluxReceive.java:388)
        at reactor.netty.channel.ChannelOperations.onInboundNext(ChannelOperations.java:404)
        at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
```
@rusher

**Comment by mindfn** [comment]
@rusher

**Comment by mindfn** [comment]
I submitted a [PR](https://github.com/mariadb-corporation/mariadb-connector-r2dbc/pull/37)  to fix this.
