### ISSUE TITLE
Binary fields are written as ByteArray but read as String

### ISSUE THREAD

**Issue by vfouqueron** [mariadb-corporation/mariadb-connector-r2dbc#39]
I'm using the connector with Spring R2dbc data library. I'm trying to write an UUID field as a binary (MariaDB 10.6).
On insertion, I have a custom converter from UUID to ByteBuffer that works fine and data is correctly inserted. However, when reading the data, I'm going through the default StringToUUIDConverter, except that input is the binary data put in a string :
`Caused by: java.lang.IllegalArgumentException: Invalid UUID string: E�ڬ��N��A�%�i
	at java.base/java.util.UUID.fromString1(UUID.java:280) ~[na:na]
	at java.base/java.util.UUID.fromString(UUID.java:258) ~[na:na]
	at org.springframework.core.convert.support.StringToUUIDConverter.convert(StringToUUIDConverter.java:37) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.core.convert.support.StringToUUIDConverter.convert(StringToUUIDConverter.java:32) ~[spring-core-5.3.22.jar:5.3.22]`

**Comment by rusher** [comment]
This is because column was created with a binary format (varbinary/blob) in place of String. connector will then return a byte array and not a string.
