### ISSUE TITLE
Unexpected message received when no command was send

### ISSUE THREAD

**Issue by jordillachmrf** [mariadb-corporation/mariadb-connector-r2dbc#50]
Hi, I am migrating from r2dbc-mysql to r2dbc-mariadb and found this error when deploying the application in production, where connection to the mysql-server pass through a mysql-router.

r2dbc-mariadb version 1.0.3
mysql-router version 8.0.28-1.0.7-router
mysql-server 8.0.30

`com.marfeel.broker.configuration.DropErrorListener$DroppedError: io.netty.handler.codec.DecoderException: io.r2dbc.spi.R2dbcNonTransientResourceException: unexpected message received when no command was send: 0xFFBF0F23485930303054686520636C69656E742077617320646973636F6E6E656374656420627920746865207365727665722062656361757365206F6620696E61637469766974792E2053656520776169745F74696D656F757420616E6420696E7465726163746976655F74696D656F757420666F7220636F6E6669677572696E672074686973206265686176696F722E
	at com.marfeel.broker.configuration.DropErrorListener.lambda$initialize$0(DropErrorListener.java:17)
	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:639)
	at reactor.core.publisher.LambdaMonoSubscriber.doError(LambdaMonoSubscriber.java:158)
	at reactor.core.publisher.LambdaMonoSubscriber.onError(LambdaMonoSubscriber.java:150)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.lambda$onError$2(MarfeelTracerAwareCoreSubscriber.java:62)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.executeTracerAware(MarfeelTracerAwareCoreSubscriber.java:75)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.onError(MarfeelTracerAwareCoreSubscriber.java:62)
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:84)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.lambda$onError$2(MarfeelTracerAwareCoreSubscriber.java:62)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.executeTracerAware(MarfeelTracerAwareCoreSubscriber.java:75)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.onError(MarfeelTracerAwareCoreSubscriber.java:62)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.lambda$onError$2(MarfeelTracerAwareCoreSubscriber.java:62)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.executeTracerAware(MarfeelTracerAwareCoreSubscriber.java:75)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.onError(MarfeelTracerAwareCoreSubscriber.java:62)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.lambda$onError$2(MarfeelTracerAwareCoreSubscriber.java:62)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.executeTracerAware(MarfeelTracerAwareCoreSubscriber.java:75)
	at com.marfeel.autoconfig.tracing.reactive.MarfeelTracerAwareCoreSubscriber.onError(MarfeelTracerAwareCoreSubscriber.java:62)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onError(FluxHide.java:142)
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:544)
	at reactor.netty.channel.FluxReceive.onInboundError(FluxReceive.java:450)
	at reactor.netty.channel.ChannelOperations.onInboundError(ChannelOperations.java:488)
	at reactor.netty.channel.ChannelOperationsHandler.exceptionCaught(ChannelOperationsHandler.java:126)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: reactor.core.Exceptions$ErrorCallbackNotImplemented: io.netty.handler.codec.DecoderException: io.r2dbc.spi.R2dbcNonTransientResourceException: unexpected message received when no command was send: 0xFFBF0F23485930303054686520636C69656E742077617320646973636F6E6E656374656420627920746865207365727665722062656361757365206F6620696E61637469766974792E2053656520776169745F74696D656F757420616E6420696E7465726163746976655F74696D656F757420666F7220636F6E6669677572696E672074686973206265686176696F722E
Caused by: io.netty.handler.codec.DecoderException: io.r2dbc.spi.R2dbcNonTransientResourceException: unexpected message received when no command was send: 0xFFBF0F23485930303054686520636C69656E742077617320646973636F6E6E656374656420627920746865207365727665722062656361757365206F6620696E61637469766974792E2053656520776169745F74696D656F757420616E6420696E7465726163746976655F74696D656F757420666F7220636F6E6669677572696E672074686973206265686176696F722E
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
	Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
	*___________________ ? at reactor.netty.channel.ChannelOperations.receiveObject(ChannelOperations.java:270)
	|_         Flux.from ? at reactor.netty.ReactorNetty.publisherOrScalarMap(ReactorNetty.java:539)
	|_          Flux.map ? at reactor.netty.ReactorNetty.publisherOrScalarMap(ReactorNetty.java:540)
	|_         Flux.from ? at reactor.netty.ByteBufFlux.fromInbound(ByteBufFlux.java:71)
	|_ Flux.doOnComplete ? at org.mariadb.r2dbc.client.ClientBase.<init>(ClientBase.java:76)
	|_         Flux.then ? at org.mariadb.r2dbc.client.ClientBase.<init>(ClientBase.java:77)
Original Stack Trace:
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
		at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
		at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.r2dbc.spi.R2dbcNonTransientResourceException: unexpected message received when no command was send: 0xFFBF0F23485930303054686520636C69656E742077617320646973636F6E6E656374656420627920746865207365727665722062656361757365206F6620696E61637469766974792E2053656520776169745F74696D656F757420616E6420696E7465726163746976655F74696D656F757420666F7220636F6E6669677572696E672074686973206265686176696F722E
	at org.mariadb.r2dbc.client.MariadbPacketDecoder.handleBuffer(MariadbPacketDecoder.java:87)
	at org.mariadb.r2dbc.client.MariadbPacketDecoder.decode(MariadbPacketDecoder.java:79)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)`

Any hint on how to proceed ? 
Thanks

**Comment by rusher** [comment]
this hexa correspond to an error "The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior" 

This is corrected in 1.1 releases
