### ISSUE TITLE
Issue with saving entities with auto generated IDs since 1.1.3

### ISSUE THREAD

**Issue by mikhilsanghvi** [mariadb-corporation/mariadb-connector-r2dbc#62]
After upgrading to 1.1.3, saving entities with AUTO GENERATED Id in DB is failing with below error

java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
Original Stack Trace:
		at java.base/java.lang.reflect.Method.invoke(Method.java:561) ~[na:na]
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:281) ~[spring-core-6.0.3.jar:6.0.3]
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:265) ~[spring-core-6.0.3.jar:6.0.3]
		at org.springframework.data.r2dbc.convert.RowMetadataUtils.getColumnMetadata(RowMetadataUtils.java:69) ~[spring-data-r2dbc-3.0.0.jar:3.0.0]
		at org.springframework.data.r2dbc.convert.RowMetadataUtils.containsColumn(RowMetadataUtils.java:46) ~[spring-data-r2dbc-3.0.0.jar:3.0.0]
		at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.extractGeneratedIdentifier(MappingR2dbcConverter.java:633) ~[spring-data-r2dbc-3.0.0.jar:3.0.0]
		at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.potentiallySetId(MappingR2dbcConverter.java:618) ~[spring-data-r2dbc-3.0.0.jar:3.0.0]
		at org.springframework.data.r2dbc.convert.MappingR2dbcConverter.lambda$populateIdIfNecessary$2(MappingR2dbcConverter.java:605) ~[spring-data-r2dbc-3.0.0.jar:3.0.0]
		at org.mariadb.r2dbc.client.MariadbResult.lambda$map$2(MariadbResult.java:164) ~[r2dbc-mariadb-1.1.3.jar:1.1.3]

**Comment by rusher** [comment]
closing, since must have been corrected in 1.2.0 with https://github.com/mariadb-corporation/mariadb-connector-r2dbc/commit/1be057679328480748edfec2924a5d9392731b19
