### ISSUE TITLE
When calling a stored procedure, an intermittent Connection Error occurs.

### ISSUE THREAD

**Issue by yjjung-jellypage** [mariadb-corporation/mariadb-connector-r2dbc#67]
Hello, while using r2dbc, the following error occurred.

------------------------------------------------------------------------------------------------------------------------

ERROR myapp.webflux.BaseErrorAttributes[getErrorAttributes] line:61 - executeMany; SQL [call usp_regular_w_login_id_post(:pi_vch_login_id, :pi_vch_passphrase, :pi_vch_salt, :pi_vch_email, :pi_chr_nickname, :pi_vch_dormant_option, :pi_vch_device_uuid, :pi_vch_os, :pi_vch_os_version, :pi_vch_device_model_name, :pi_vch_ip, :pi_vch_app_version, :pi_vch_push_token, :pi_vch_service_code, :pi_dt5_now, :po_int_return, :po_jsn_log)]; Connection error
org.springframework.dao.DataAccessResourceFailureException: executeMany; SQL [call usp_regular_w_login_id_post(:pi_vch_login_id, :pi_vch_passphrase, :pi_vch_salt, :pi_vch_email, :pi_chr_nickname, :pi_vch_dormant_option, :pi_vch_device_uuid, :pi_vch_os, :pi_vch_os_version, :pi_vch_device_model_name, :pi_vch_ip, :pi_vch_app_version, :pi_vch_push_token, :pi_vch_service_code, :pi_dt5_now, :po_int_return, :po_jsn_log)]; Connection error
        at org.springframework.r2dbc.connection.ConnectionFactoryUtils.convertR2dbcException(ConnectionFactoryUtils.java:231)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
        *__checkpoint ⇢ Handler jelly.front.account.adapter.in.web.AccountController#jelly_join(JoinJellyForm) [DispatcherHandler]
        *__checkpoint ⇢ myapp.webflux.filter.JellyHeaderWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ myapp.auth.front.jwt.DefaultAuthenticationWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP POST "/account/myapp/join" [ExceptionHandlingWebHandler]

Caused by: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(17) exceeds writerIndex(13): PooledSlicedByteBuf(ridx: 9, widx: 13, cap: 13/13, unwrapped: PooledUnsafeDirectByteBuf(ridx: 27, widx: 495, cap: 512))
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1589)

------------------------------------------------------------------------------------------------------------------------

The issue is that this error occurs very intermittently.

The execution environment is as follows:
------------------------------------------------------------------------------------------------------------------------
        <dependency>
            <groupId>org.mariadb</groupId>
            <artifactId>r2dbc-mariadb</artifactId>
            <version>1.1.3</version>
        </dependency>

        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.1.2</version>
        </dependency>

JDK 20
Spring Boot 3.0.4
------------------------------------------------------------------------------------------------------------------------

I would appreciate your help. Thank you.

**Comment by rusher** [comment]
This is probably due to https://jira.mariadb.org/browse/R2DBC-76, did you have tryed with 1.1.4 ?

**Comment by rusher** [comment]
closing since no answer
