### ISSUE TITLE
NPE in BufferUtils.writeLengthEncode()

### ISSUE THREAD

**Issue by mdeso** [mariadb-corporation/mariadb-connector-r2dbc#78]
When starting a Micronaut 4 application I get an NPE from within `BufferUtils.writeLlengthEncode()`:
```java
Caused by: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "val" is null
        at org.mariadb.r2dbc.util.BufferUtils.writeLengthEncode(BufferUtils.java:103)
        at org.mariadb.r2dbc.message.client.HandshakeResponse.writeConnectAttributes(HandshakeResponse.java:168)
        at org.mariadb.r2dbc.message.client.HandshakeResponse.encode(HandshakeResponse.java:143)
        at org.mariadb.r2dbc.client.MariadbPacketEncoder.encodeFlux(MariadbPacketEncoder.java:20)
        at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:113)
```
The causing line is
```java
BufferUtils.writeLengthEncode(properties.getProperty("version"), buf);
```
The code there seems strange to me. It tries to read a file `project.properties`, as it seems from anywhere on the classpath. If that file isn't found it silently "eats" the signalling IOException. But if it is found it tries to read the _version_ property from it and write it to the buffer as `_client_version`. And if the _version_ property doesn't exist this causes the NPE. I would say this read-properties block should be removed completely, it makes no sense as it is completely optional. In my case it found a `project.properties` in some dependency which didn't contain the expected property, causing the NPE. 

A  workaround is to place a dummy "project.properties" with a _version_ property in the classpath before any other potential candidate (which may be difficult under certain circumstances).

**Comment by rusher** [comment]
This will be in 1.2.1 release.

Snapshot available on sonatype nexus repository:
```

<repositories>
	<repository>
		<id>sonatype-nexus-snapshots</id>
		<name>Sonatype Nexus Snapshots</name>
		<url>https://oss.sonatype.org/content/repositories/snapshots</url>
	</repository>
</repositories>

<dependency>
    <groupId>org.mariadb</groupId>
    <artifactId>r2dbc-mariadb</artifactId>
    <version>1.2.1-SNAPSHOT</version>
</dependency>
```
